export const GAME_CONFIG = {
  AMUSEMENT_ID: 7,
  GROUP_ID: 6,
  COST: 3,
  CURRENCY: "€",
  API_KEY: import.meta.env.API_KEY,
  STAMP_ID: 2,
  JACKPOT_MULTIPLIER: 5,
  JACKPOT_BONUS_STAMP_ID: 15,
  DOUBLE_WIN_MULTIPLIER: 2,
};
